"""Static NANP area-code geography.

Public city/state only. No reverse-phone, skip-tracing, or paid lookup.
Shop is Irondale AL: 205/659 are local Birmingham; other AL codes are in-state.
"""

from __future__ import annotations

import re

# Shop-local Birmingham overlays (Irondale sits in 205).
LOCAL_AREA_CODES = frozenset({"205", "659"})

# All Alabama NPAs, including overlays in service or assigned.
ALABAMA_AREA_CODES = frozenset({"205", "251", "256", "334", "659", "938", "483"})

TOLL_FREE = frozenset({"800", "833", "844", "855", "866", "877", "888"})

# code -> (metro, state abbreviation). Dump labels for this shop win over generics.
AREA_CODES: dict[str, tuple[str, str]] = {
    "201": ('Hudson County / Jersey City', 'NJ'),
    "202": ('Washington', 'DC'),
    "203": ('Bridgeport / New Haven', 'CT'),
    "205": ('Birmingham / Irondale', 'AL'),
    "206": ('Seattle', 'WA'),
    "207": ('Maine', 'ME'),
    "208": ('Idaho', 'ID'),
    "209": ('Stockton / Modesto', 'CA'),
    "210": ('San Antonio', 'TX'),
    "212": ('Manhattan', 'NY'),
    "213": ('Los Angeles', 'CA'),
    "214": ('Dallas', 'TX'),
    "215": ('Philadelphia', 'PA'),
    "216": ('Cleveland', 'OH'),
    "217": ('Springfield / Champaign', 'IL'),
    "218": ('N. Minnesota / Duluth', 'MN'),
    "219": ('NW Indiana / Gary', 'IN'),
    "220": ('Central Ohio overlay', 'OH'),
    "223": ('Harrisburg overlay', 'PA'),
    "224": ('N. Chicago suburbs overlay', 'IL'),
    "225": ('Baton Rouge', 'LA'),
    "228": ('Gulfport / Biloxi', 'MS'),
    "229": ('Albany GA', 'GA'),
    "231": ('NW Michigan', 'MI'),
    "234": ('Akron overlay', 'OH'),
    "239": ('SW Florida', 'FL'),
    "240": ('W. Maryland overlay', 'MD'),
    "248": ('Oakland County', 'MI'),
    "251": ('Mobile', 'AL'),
    "252": ('E. North Carolina / Greenville', 'NC'),
    "253": ('Tacoma', 'WA'),
    "254": ('Waco / Killeen', 'TX'),
    "256": ('Huntsville / north AL', 'AL'),
    "260": ('Fort Wayne', 'IN'),
    "262": ('SE Wisconsin suburbs', 'WI'),
    "267": ('Philadelphia overlay', 'PA'),
    "269": ('SW Michigan / Kalamazoo', 'MI'),
    "270": ('W. Kentucky', 'KY'),
    "272": ('NE Pennsylvania overlay', 'PA'),
    "274": ('Green Bay overlay', 'WI'),
    "276": ('SW Virginia', 'VA'),
    "279": ('Sacramento overlay', 'CA'),
    "281": ('Houston suburbs', 'TX'),
    "283": ('Cincinnati overlay', 'OH'),
    "301": ('W. Maryland / DC suburbs', 'MD'),
    "302": ('Delaware', 'DE'),
    "303": ('Denver', 'CO'),
    "304": ('West Virginia', 'WV'),
    "305": ('Miami', 'FL'),
    "307": ('Wyoming', 'WY'),
    "308": ('W. Nebraska', 'NE'),
    "309": ('Peoria / Bloomington', 'IL'),
    "310": ('West LA / South Bay', 'CA'),
    "312": ('Chicago', 'IL'),
    "313": ('Detroit', 'MI'),
    "314": ('St. Louis', 'MO'),
    "315": ('Syracuse', 'NY'),
    "316": ('Wichita', 'KS'),
    "317": ('Indianapolis', 'IN'),
    "318": ('Shreveport / N. Louisiana', 'LA'),
    "319": ('Cedar Rapids / Iowa City', 'IA'),
    "320": ('Central Minnesota', 'MN'),
    "321": ('Orlando overlay', 'FL'),
    "323": ('Los Angeles overlay', 'CA'),
    "324": ('North Florida overlay', 'FL'),
    "325": ('Abilene / San Angelo', 'TX'),
    "326": ('Dayton overlay', 'OH'),
    "329": ('Hudson Valley overlay', 'NY'),
    "330": ('Akron / Canton', 'OH'),
    "331": ('W. Chicago suburbs overlay', 'IL'),
    "332": ('Manhattan overlay', 'NY'),
    "334": ('Montgomery', 'AL'),
    "336": ('Greensboro', 'NC'),
    "337": ('Lafayette LA', 'LA'),
    "339": ('Boston suburbs overlay', 'MA'),
    "340": ('U.S. Virgin Islands', 'VI'),
    "341": ('Oakland overlay', 'CA'),
    "346": ('Houston overlay', 'TX'),
    "347": ('NYC outer boroughs overlay', 'NY'),
    "350": ('Stockton overlay', 'CA'),
    "351": ('N. Massachusetts overlay', 'MA'),
    "352": ('Gainesville / Ocala', 'FL'),
    "353": ('Madison overlay', 'WI'),
    "357": ('San Joaquin overlay', 'CA'),
    "360": ('W. Washington (non-metro)', 'WA'),
    "361": ('Corpus Christi / S. TX', 'TX'),
    "363": ('Long Island overlay', 'NY'),
    "364": ('W. Kentucky overlay', 'KY'),
    "369": ('Santa Rosa overlay', 'CA'),
    "380": ('Columbus overlay', 'OH'),
    "385": ('Utah overlay', 'UT'),
    "386": ('Daytona / N. Florida', 'FL'),
    "401": ('Rhode Island', 'RI'),
    "402": ('Omaha / Lincoln', 'NE'),
    "404": ('Atlanta', 'GA'),
    "405": ('Oklahoma City', 'OK'),
    "406": ('Montana', 'MT'),
    "407": ('Orlando', 'FL'),
    "408": ('San Jose', 'CA'),
    "409": ('Beaumont / Galveston', 'TX'),
    "410": ('Baltimore / E. Maryland', 'MD'),
    "412": ('Pittsburgh', 'PA'),
    "413": ('W. Massachusetts / Springfield', 'MA'),
    "414": ('Milwaukee', 'WI'),
    "415": ('San Francisco', 'CA'),
    "417": ('Springfield / Joplin', 'MO'),
    "419": ('Toledo / NW Ohio', 'OH'),
    "423": ('Chattanooga / E. TN', 'TN'),
    "424": ('West LA overlay', 'CA'),
    "425": ('Eastside / Bellevue / Everett', 'WA'),
    "430": ('Tyler overlay', 'TX'),
    "432": ('Midland / Odessa', 'TX'),
    "434": ('Charlottesville / Lynchburg', 'VA'),
    "435": ('S. / E. Utah', 'UT'),
    "436": ('Toledo overlay', 'OH'),
    "440": ('Cleveland suburbs', 'OH'),
    "442": ('Inland / Imperial overlay', 'CA'),
    "443": ('Baltimore overlay', 'MD'),
    "445": ('Philadelphia overlay', 'PA'),
    "447": ('Springfield overlay', 'IL'),
    "448": ('FL panhandle overlay', 'FL'),
    "458": ('Eugene overlay', 'OR'),
    "463": ('Indianapolis overlay', 'IN'),
    "464": ('S. Chicago suburbs overlay', 'IL'),
    "465": ('NYC outer boroughs overlay', 'NY'),
    "469": ('Dallas overlay', 'TX'),
    "470": ('Atlanta overlay', 'GA'),
    "471": ('N. Mississippi overlay', 'MS'),
    "472": ('Greensboro overlay', 'NC'),
    "475": ('Bridgeport overlay', 'CT'),
    "478": ('Macon', 'GA'),
    "479": ('Fort Smith / Fayetteville', 'AR'),
    "480": ('Phoenix E. Valley', 'AZ'),
    "483": ('Montgomery', 'AL'),
    "484": ('SE Pennsylvania', 'PA'),
    "501": ('Little Rock', 'AR'),
    "502": ('Louisville', 'KY'),
    "503": ('Portland OR', 'OR'),
    "504": ('New Orleans', 'LA'),
    "505": ('New Mexico', 'NM'),
    "507": ('S. Minnesota / Rochester', 'MN'),
    "508": ('Worcester / Cape Cod', 'MA'),
    "509": ('E. Washington / Spokane', 'WA'),
    "510": ('Oakland / East Bay', 'CA'),
    "512": ('Austin', 'TX'),
    "513": ('Cincinnati', 'OH'),
    "515": ('Des Moines', 'IA'),
    "516": ('Long Island', 'NY'),
    "517": ('Lansing', 'MI'),
    "518": ('Albany / Capital Region', 'NY'),
    "520": ('Tucson', 'AZ'),
    "530": ('N. California', 'CA'),
    "531": ('Omaha overlay', 'NE'),
    "534": ('W. Wisconsin overlay', 'WI'),
    "539": ('Tulsa overlay', 'OK'),
    "540": ('W. Virginia / Roanoke', 'VA'),
    "541": ('Eugene / E. Oregon', 'OR'),
    "551": ('Hudson County overlay', 'NJ'),
    "557": ('St. Louis overlay', 'MO'),
    "559": ('Fresno', 'CA'),
    "561": ('West Palm Beach', 'FL'),
    "562": ('Long Beach', 'CA'),
    "563": ('Quad Cities / Dubuque', 'IA'),
    "564": ('W. Washington overlay', 'WA'),
    "565": ('Savannah overlay', 'GA'),
    "567": ('Toledo overlay', 'OH'),
    "570": ('NE Pennsylvania / Scranton', 'PA'),
    "571": ('N. Virginia overlay', 'VA'),
    "572": ('Oklahoma City overlay', 'OK'),
    "573": ('Missouri', 'MO'),
    "574": ('South Bend / Elkhart', 'IN'),
    "575": ('S. New Mexico / Las Cruces', 'NM'),
    "580": ('W. Oklahoma', 'OK'),
    "582": ('NW Pennsylvania overlay', 'PA'),
    "585": ('Rochester', 'NY'),
    "586": ('Macomb County', 'MI'),
    "601": ('Jackson MS', 'MS'),
    "602": ('Phoenix', 'AZ'),
    "603": ('New Hampshire', 'NH'),
    "605": ('South Dakota', 'SD'),
    "606": ('E. Kentucky', 'KY'),
    "607": ('S. New York', 'NY'),
    "608": ('Madison', 'WI'),
    "609": ('Trenton / Atlantic City', 'NJ'),
    "610": ('SE Pennsylvania', 'PA'),
    "612": ('Minneapolis', 'MN'),
    "614": ('Columbus OH', 'OH'),
    "615": ('Nashville', 'TN'),
    "616": ('Grand Rapids', 'MI'),
    "617": ('Boston', 'MA'),
    "618": ('S. Illinois', 'IL'),
    "619": ('San Diego', 'CA'),
    "620": ('S. Kansas', 'KS'),
    "623": ('Phoenix W. Valley', 'AZ'),
    "624": ('Buffalo overlay', 'NY'),
    "626": ('Pasadena / SGV', 'CA'),
    "628": ('San Francisco overlay', 'CA'),
    "629": ('Nashville overlay', 'TN'),
    "630": ('W. Chicago suburbs', 'IL'),
    "631": ('Suffolk County NY', 'NY'),
    "636": ('St. Louis suburbs', 'MO'),
    "640": ('Trenton overlay', 'NJ'),
    "641": ('Central Iowa', 'IA'),
    "645": ('Miami overlay', 'FL'),
    "646": ('New York overlay', 'NY'),
    "650": ('San Mateo / Peninsula', 'CA'),
    "651": ('St. Paul', 'MN'),
    "656": ('Tampa overlay', 'FL'),
    "657": ('Orange County overlay', 'CA'),
    "659": ('Birmingham overlay', 'AL'),
    "660": ('N. Missouri', 'MO'),
    "661": ('Bakersfield / Antelope Valley', 'CA'),
    "662": ('N. Mississippi', 'MS'),
    "667": ('Baltimore overlay', 'MD'),
    "669": ('San Jose overlay', 'CA'),
    "670": ('Northern Mariana Islands', 'MP'),
    "671": ('Guam', 'GU'),
    "678": ('Atlanta overlay', 'GA'),
    "680": ('Syracuse overlay', 'NY'),
    "681": ('West Virginia overlay', 'WV'),
    "682": ('Fort Worth overlay', 'TX'),
    "684": ('American Samoa', 'AS'),
    "686": ('N. Virginia overlay', 'VA'),
    "689": ('Orlando overlay', 'FL'),
    "701": ('North Dakota', 'ND'),
    "702": ('Las Vegas', 'NV'),
    "703": ('N. Virginia', 'VA'),
    "704": ('Charlotte', 'NC'),
    "706": ('N. Georgia / Columbus GA', 'GA'),
    "707": ('Santa Rosa / Napa', 'CA'),
    "708": ('S. Chicago suburbs', 'IL'),
    "712": ('W. Iowa / Sioux City', 'IA'),
    "713": ('Houston', 'TX'),
    "714": ('Orange County', 'CA'),
    "715": ('N. Wisconsin', 'WI'),
    "716": ('Buffalo', 'NY'),
    "717": ('Harrisburg', 'PA'),
    "718": ('NYC outer boroughs', 'NY'),
    "719": ('Colorado Springs', 'CO'),
    "720": ('Denver overlay', 'CO'),
    "724": ('W. Pennsylvania', 'PA'),
    "725": ('Las Vegas overlay', 'NV'),
    "726": ('San Antonio overlay', 'TX'),
    "727": ('St. Petersburg / Pinellas', 'FL'),
    "728": ('West Palm overlay', 'FL'),
    "729": ('E. Tennessee overlay', 'TN'),
    "730": ('S. Illinois overlay', 'IL'),
    "731": ('W. Tennessee', 'TN'),
    "732": ('Central Jersey', 'NJ'),
    "734": ('Ann Arbor / W. Detroit', 'MI'),
    "737": ('Austin overlay', 'TX'),
    "738": ('Los Angeles overlay', 'CA'),
    "740": ('SE Ohio', 'OH'),
    "743": ('Charlotte overlay', 'NC'),
    "747": ('San Fernando Valley overlay', 'CA'),
    "748": ('W. Colorado overlay', 'CO'),
    "754": ('Broward overlay', 'FL'),
    "757": ('Hampton Roads', 'VA'),
    "760": ('Inland / Imperial / High Desert', 'CA'),
    "761": ('Louisville overlay', 'KY'),
    "762": ('N. Georgia overlay', 'GA'),
    "763": ('NW Twin Cities', 'MN'),
    "765": ('Indiana', 'IN'),
    "769": ('Jackson overlay', 'MS'),
    "770": ('Atlanta suburbs', 'GA'),
    "771": ('Washington overlay', 'DC'),
    "772": ('Treasure Coast', 'FL'),
    "773": ('Chicago overlay', 'IL'),
    "774": ('Worcester overlay', 'MA'),
    "775": ('N. Nevada / Reno', 'NV'),
    "779": ('N. Illinois overlay', 'IL'),
    "781": ('Boston suburbs', 'MA'),
    "785": ('Topeka / W. Kansas', 'KS'),
    "786": ('Miami overlay', 'FL'),
    "787": ('Puerto Rico', 'PR'),
    "800": ('Toll-free', ''),
    "801": ('Salt Lake City', 'UT'),
    "802": ('Vermont', 'VT'),
    "803": ('Columbia SC', 'SC'),
    "804": ('Richmond', 'VA'),
    "805": ('Ventura / Santa Barbara / SLO', 'CA'),
    "806": ('Lubbock / Amarillo', 'TX'),
    "808": ('Hawaii', 'HI'),
    "810": ('Flint / Thumb', 'MI'),
    "812": ('S. Indiana', 'IN'),
    "813": ('Tampa', 'FL'),
    "814": ('Central / NW Pennsylvania', 'PA'),
    "815": ('N. Illinois', 'IL'),
    "816": ('Kansas City MO', 'MO'),
    "817": ('Fort Worth', 'TX'),
    "818": ('San Fernando Valley', 'CA'),
    "820": ('Ventura overlay', 'CA'),
    "826": ('Roanoke overlay', 'VA'),
    "828": ('Asheville / W. NC', 'NC'),
    "830": ('Texas Hill Country', 'TX'),
    "831": ('Monterey / Santa Cruz', 'CA'),
    "832": ('Houston overlay', 'TX'),
    "833": ('Toll-free', ''),
    "835": ('SE Pennsylvania overlay', 'PA'),
    "837": ('Sacramento overlay', 'CA'),
    "838": ('Albany overlay', 'NY'),
    "839": ('Columbia overlay', 'SC'),
    "840": ('Inland Empire overlay', 'CA'),
    "843": ('Charleston / Myrtle Beach', 'SC'),
    "844": ('Toll-free', ''),
    "845": ('Hudson Valley', 'NY'),
    "847": ('N. Chicago suburbs', 'IL'),
    "848": ('Central Jersey overlay', 'NJ'),
    "850": ('FL panhandle', 'FL'),
    "854": ('Charleston overlay', 'SC'),
    "855": ('Toll-free', ''),
    "856": ('S. Jersey / Camden', 'NJ'),
    "857": ('Boston overlay', 'MA'),
    "858": ('San Diego overlay', 'CA'),
    "859": ('Lexington', 'KY'),
    "860": ('Hartford', 'CT'),
    "861": ('N. Chicago suburbs overlay', 'IL'),
    "862": ('N. New Jersey overlay', 'NJ'),
    "863": ('Lakeland / central FL', 'FL'),
    "864": ('Greenville / Spartanburg', 'SC'),
    "865": ('Knoxville', 'TN'),
    "866": ('Toll-free', ''),
    "870": ('Jonesboro / S. Arkansas', 'AR'),
    "872": ('Chicago overlay', 'IL'),
    "877": ('Toll-free', ''),
    "878": ('Pittsburgh overlay', 'PA'),
    "888": ('Toll-free', ''),
    "901": ('Memphis', 'TN'),
    "903": ('Tyler / NE Texas', 'TX'),
    "904": ('Jacksonville', 'FL'),
    "906": ('Upper Peninsula', 'MI'),
    "907": ('Alaska', 'AK'),
    "908": ('Central / W. Jersey', 'NJ'),
    "909": ('Inland Empire CA', 'CA'),
    "910": ('SE North Carolina', 'NC'),
    "912": ('Savannah', 'GA'),
    "913": ('Kansas City KS', 'KS'),
    "914": ('Westchester', 'NY'),
    "915": ('El Paso', 'TX'),
    "916": ('Sacramento', 'CA'),
    "917": ('New York overlay', 'NY'),
    "918": ('Tulsa', 'OK'),
    "919": ('Raleigh / Durham', 'NC'),
    "920": ('Green Bay / Fox Valley', 'WI'),
    "924": ('Twin Cities overlay', 'MN'),
    "925": ('E. Bay suburbs', 'CA'),
    "928": ('N. Arizona', 'AZ'),
    "929": ('NYC overlay', 'NY'),
    "930": ('S. Indiana overlay', 'IN'),
    "931": ('Middle Tennessee', 'TN'),
    "934": ('Suffolk overlay', 'NY'),
    "936": ('E. Texas / Huntsville TX', 'TX'),
    "937": ('Dayton', 'OH'),
    "938": ('Huntsville', 'AL'),
    "939": ('Puerto Rico overlay', 'PR'),
    "940": ('Wichita Falls / Denton', 'TX'),
    "941": ('Sarasota / SW FL', 'FL'),
    "943": ('Atlanta overlay', 'GA'),
    "945": ('Dallas overlay', 'TX'),
    "947": ('Oakland County overlay', 'MI'),
    "948": ('Hampton Roads overlay', 'VA'),
    "949": ('S. Orange County', 'CA'),
    "951": ('Riverside', 'CA'),
    "952": ('SW Twin Cities', 'MN'),
    "954": ('Broward / Fort Lauderdale', 'FL'),
    "956": ('McAllen / Laredo / RGV', 'TX'),
    "959": ('Hartford overlay', 'CT'),
    "970": ('W. Colorado', 'CO'),
    "971": ('Portland overlay', 'OR'),
    "972": ('Dallas overlay', 'TX'),
    "973": ('N. New Jersey', 'NJ'),
    "975": ('Kansas City overlay', 'MO'),
    "978": ('N. Massachusetts', 'MA'),
    "979": ('Bryan / College Station / Brazos', 'TX'),
    "980": ('Charlotte overlay', 'NC'),
    "983": ('Denver overlay', 'CO'),
    "984": ('Raleigh overlay', 'NC'),
    "985": ('SE Louisiana', 'LA'),
    "986": ('Idaho overlay', 'ID'),
    "989": ('Central Michigan', 'MI'),
}

_DIGIT_RE = re.compile(r"\D+")


def phone_digits(phone: str | None) -> str:
    """NANP digits, stripping a leading country-code 1 when present."""
    if not phone:
        return ""
    digits = _DIGIT_RE.sub("", str(phone))
    if len(digits) == 11 and digits.startswith("1"):
        digits = digits[1:]
    return digits


def extract_area_code(phone: str | None) -> str:
    digits = phone_digits(phone)
    if len(digits) >= 10:
        return digits[:3]
    return ""


def format_phone(phone: str | None) -> str:
    """Display as (205) 555-0100. Empty string if not a 10-digit NANP number."""
    digits = phone_digits(phone)
    if len(digits) == 10:
        return f"({digits[:3]}) {digits[3:6]}-{digits[6:]}"
    return (phone or "").strip()


def region_for(area_code: str) -> str:
    """local | alabama | out_of_state | unknown"""
    if not area_code:
        return "unknown"
    if area_code in LOCAL_AREA_CODES:
        return "local"
    if area_code in ALABAMA_AREA_CODES:
        return "alabama"
    if area_code in TOLL_FREE:
        return "unknown"
    if area_code in AREA_CODES:
        return "out_of_state"
    return "unknown"


def lookup_code(area_code: str | None) -> dict[str, str]:
    code = (area_code or "").strip()
    if not code:
        return {"area_code": "", "area_metro": "Unknown", "area_state": "", "area_region": "unknown"}
    metro, state = AREA_CODES.get(code, ("Unknown", ""))
    region = region_for(code) if metro != "Unknown" or code in ALABAMA_AREA_CODES else "unknown"
    if metro == "Unknown" and code in ALABAMA_AREA_CODES:
        metro = "Alabama"
        state = "AL"
        region = region_for(code)
    if metro == "Toll-free":
        region = "unknown"
    return {
        "area_code": code,
        "area_metro": metro,
        "area_state": state,
        "area_region": region,
    }


def lookup_phone(phone: str | None) -> dict[str, str]:
    return lookup_code(extract_area_code(phone))

